name: First workflow
on: workflow_dispatch
jobs:
 first_job:
   runs-on: ubuntu_latest
   steps:
     - name: first job
       run: echo "my name is satya"
     - name: second  job
       run: echo "great job satya"
